steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.12.0'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Compile and package'

- script: |
    npm run package-extension
  displayName: 'Compile and package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: CopyFiles@2
  inputs:
    Contents: '**/*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)''